arch:
- amd64
- arm64
language: bash
script:
- "true"
deploy:
  provider: script
  skip_cleanup: true
  script: curl -sSL https://raw.githubusercontent.com/ManageIQ/manageiq.github.io/build/trigger.sh | bash -s
  on:
    branch: master
